# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "capistrano_mailer"
  s.version = "4.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Boling", "Dave Nolan", "Jason Rust"]
  s.date = "2011-12-11"
  s.description = "Capistrano Deployment Email Notification.  Keep the whole team informed of each release!"
  s.email = ["peter.boling@gmail.com", "dave@textgoeshere.org.uk", "jason@rustedcode.com"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "capistrano_mailer.gemspec",
    "lib/cap_mailer.rb",
    "lib/capistrano/mailer.rb",
    "views/cap_mailer/_section.html.erb",
    "views/cap_mailer/_section.text.erb",
    "views/cap_mailer/_section_custom.html.erb",
    "views/cap_mailer/_section_custom.text.erb",
    "views/cap_mailer/notification_email.html.erb",
    "views/cap_mailer/notification_email.text.erb"
  ]
  s.homepage = "http://github.com/pboling/capistrano_mailer"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Capistrano Deployment Email Notification"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionmailer>, [">= 0"])
    else
      s.add_dependency(%q<actionmailer>, [">= 0"])
    end
  else
    s.add_dependency(%q<actionmailer>, [">= 0"])
  end
end

